import jsPDF from 'jspdf'

interface Finding {
  id: string
  ruleId: string
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info'
  title: string
  description: string
  remediation: string
}

interface ScanResult {
  scanId: string
  type: 'github' | 'website'
  targetUrl: string
  severityCounts: Record<string, number>
  findings: Finding[]
  scannedAt: string
}

const SEVERITY_COLORS = {
  critical: [220, 38, 38],   // red
  high: [249, 115, 22],     // orange
  medium: [234, 179, 8],    // yellow
  low: [59, 130, 246],      // blue
  info: [100, 116, 139],    // slate
}

export function generatePDF(result: ScanResult): jsPDF {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = 20
  
  // Colors
  const emerald = [16, 185, 129]
  const slate = [51, 65, 85]
  const lightSlate = [248, 250, 252]
  
  // Header background
  doc.setFillColor(emerald[0], emerald[1], emerald[2])
  doc.rect(0, 0, pageWidth, 45, 'F')
  
  // Title
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('VibeChecker Security Report', margin, 25)
  
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated: ${new Date(result.scannedAt).toLocaleString()}`, margin, 35)
  
  y = 55
  
  // Target info
  doc.setTextColor(slate[0], slate[1], slate[2])
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Scan Target', margin, y)
  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(result.targetUrl, margin, y)
  y += 10
  
  // Summary box
  doc.setFillColor(lightSlate[0], lightSlate[1], lightSlate[2])
  doc.roundedRect(margin, y, pageWidth - margin * 2, 35, 3, 3, 'F')
  
  y += 10
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Summary', margin + 5, y)
  y += 8
  
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const severities = ['critical', 'high', 'medium', 'low', 'info']
  let x = margin + 5
  for (const sev of severities) {
    const count = result.severityCounts[sev] || 0
    if (count > 0) {
      const sevColor = SEVERITY_COLORS[sev as keyof typeof SEVERITY_COLORS]
      doc.setTextColor(sevColor[0], sevColor[1], sevColor[2])
      doc.text(`${count} ${sev.toUpperCase()}`, x, y)
      x += doc.getTextWidth(`${count} ${sev.toUpperCase()}  `)
    }
  }
  
  y += 20
  
  // Findings
  doc.setTextColor(slate[0], slate[1], slate[2])
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Findings', margin, y)
  y += 10
  
  // Sort findings by severity
  const sortedFindings = [...result.findings].sort((a, b) => {
    const order = { critical: 0, high: 1, medium: 2, low: 3, info: 4 }
    return order[a.severity] - order[b.severity]
  })
  
  for (const finding of sortedFindings) {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage()
      y = 20
    }
    
    // Severity badge
    const [r, g, b] = SEVERITY_COLORS[finding.severity]
    doc.setFillColor(r, g, b)
    doc.roundedRect(margin, y, 35, 8, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text(finding.severity.toUpperCase(), margin + 3, y + 5.5)
    
    // Title
    doc.setTextColor(slate[0], slate[1], slate[2])
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(finding.title, margin + 42, y + 5.5)
    y += 12
    
    // Rule ID
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.text(`Rule: ${finding.ruleId}`, margin, y)
    y += 6
    
    // Description
    doc.setTextColor(71, 85, 105)
    doc.setFontSize(9)
    const descLines = doc.splitTextToSize(finding.description, pageWidth - margin * 2)
    doc.text(descLines, margin, y)
    y += descLines.length * 4 + 4
    
    // Remediation
    doc.setFillColor(236, 253, 245)
    doc.roundedRect(margin, y, pageWidth - margin * 2, 20, 2, 2, 'F')
    y += 5
    
    doc.setTextColor(22, 101, 52)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.text('RECOMMENDED FIX:', margin + 3, y)
    y += 5
    
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(34, 85, 51)
    const fixLines = doc.splitTextToSize(finding.remediation, pageWidth - margin * 2 - 6)
    doc.text(fixLines, margin + 3, y)
    y += fixLines.length * 4 + 10
    
    // Divider line
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.5)
    doc.line(margin, y - 5, pageWidth - margin, y - 5)
  }
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15
  doc.setTextColor(148, 163, 184)
  doc.setFontSize(8)
  doc.text('Generated by VibeChecker - Free Vibe Coding Security Scanner', pageWidth / 2, footerY, { align: 'center' })
  doc.text(`Scan ID: ${result.scanId}`, pageWidth / 2, footerY + 5, { align: 'center' })
  
  return doc
}

export function downloadPDF(result: ScanResult) {
  const doc = generatePDF(result)
  const filename = `vibechecker-report-${result.type}-${new Date(result.scannedAt).toISOString().slice(0, 10)}.pdf`
  doc.save(filename)
}
